FROM ft-laravel
EXPOSE 8000
ENTRYPOINT php artisan serve --host=0.0.0.0

###### CHECK ######
# docker build -t laravel-app ./
# docker run --rm -it -p 8000:8000 laravel-app
# go to browser localhost:8000